### ISSUE TITLE
Piping back to res to the client

### ISSUE THREAD

**Issue by rockyhuber** [lammas/flac-substream#1]
Hi Iammas,

Love what you have created with this. Any ideas/guidance you can offer on piping this data back to the client via the res?

I would like to read the flac audio and stream a portion of the flac audio file back to the client. I have managed to get the stream data sent back down, though am struggling with what headers to the set on the response to get it to play?

Ideally I wouldn't create a separate file and just stream the audio directly, So I am going to have to directly edit the flac-substream to make this happen.

Any suggestions that you can provide on the  'Accept-Ranges', 'Content-Type', 'Content-Length' and 'Content-Range'?

**Comment by lammas** [comment]
Not quite sure I understand the problem. The substream library prepends the original flac file's header to the returned flac audio data (and updates the number of samples present). 
You can then send that binary data stream over HTTP as you would send a reguler flac file stream.

Feel free to clarify your issue and I will try my best to help. :)

**Comment by rockyhuber** [comment]
Thank you for your quick reply!

I am trying to set the response headers in Nodejs, to stream the flac file back to the client. I have tried piping in directly like in your example, however that did not work. I presume I have to set the response headers before being able to make this work? Something like this?

```
   res.writeHead(206, {
        "Content-Range": "bytes " + start + "-" + end + "/" + total,
        "Accept-Ranges": "bytes",
        "Content-Length": chunksize,
        "Content-Type": "video/mp4"
      });
```

In my example, all I did was try to pipe stream to the response.

```
   var reader = fs.createReadStream(pathin);

            reader.pipe(new seektable(function(data) {
                var output = fs.createWriteStream(pathin, { flags: 'w' });

                substream(pathout, data, 10, 20, function (start, end) {
                    var stream = fs.createReadStream(
                        pathin,
                        {
                            start: start,
                            end: end
                        }
                    );
                    return stream;
                });
            })).pipe(res); //  <--- here
```
I also tried to send the data down to the client by the readstream method like so:

```
var stream = fs.createReadStream(
                        pathin,
                        {
                            start: start,
                            end: end
                        }
                    );
stream.on('data', chunk => {
      res.write(chunk);
});
```
Though that didn't work either. Pardon my ignorance in this area. Audio is new to me.

Thank you again for your help.

**Comment by rockyhuber** [comment]
Ok, so phrasing it in hopefully a more concise manner. We got it to work to put it through the server response with header, however we want the audio to be able to be seekable stream on the client side. Like streaming in 206 Partial Content chunks. Is it possible with any html native audio player?

**Comment by lammas** [comment]
I'm currently not familiar if the native audio player in browsers sends Range requests for flac streams or not. Assuming it does you could use the flac-seektable information directly and would not need to use this library at all. You could just look up the right offset from the seektable and request a range using that info.
